version: '3'

services:
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    environment:
      MYSQL_DATABASE: bookapi
      MYSQL_USER: user
      MYSQL_PASSWORD: pass1234
      MYSQL_ROOT_PASSWORD: p@ssworb
    ports:
      - 3306:3306

  book-api:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookapi?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
