spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:mysql://localhost:3306/bookapi
    username: user
    password: pass1234
    initialization-mode: always
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        c3p0:
          min_size: 5
          max_size: 20
          acquire_increment: 1
          timeout: 1800
          max_statements: 150
        hbm2ddl:
          auto: validate
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
