spring:
  main:
    banner-mode: "off"
  datasource:
    username: user
    password: pass1234
    initialization-mode: embedded
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        c3p0:
          min_size: 5
          max_size: 20
          acquire_increment: 1
          timeout: 1800
          max_statements: 150
        hbm2ddl:
          auto: validate
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
